version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'mysql57-web'
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: mysqldb
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
